AERA-Pik/kitty-cakes-proyecto-integrador-generation

readme.txt

Se agregó únicamente mi nombre a los "Integrantes del equipo"

Corrección a "Integrantes del equipo"

---

index.html
src/assets/css/nav-style.css

Se va agregar el index con el navbar y cambios a estilos de css

navbar responsivo

---

src/index.html

Modificación a la etiqueta src de las imágenes para coincidir con las rutas después de moverlo de carpeta

Se movio el archivo index a la carpeta src y se modifico

---

src/assets/css/login-style.css
src/login.html

Se sube la parte del Login y aun esta sujeta a posibles cambios.

Diseño html y css de Login

---

src/index.html
src/plantilla.html

@oscar10909 @VictorH2ernandez  @Leticia-Somera  @danielgarcianu  @BalfonsoBH  @010278Francisco @AERA-Pik

archivo index con sección de home-correción

---

src/carrito.html

Agregados enlaces en pagina carrito @oscar10909 @KARLA-LEON @VictorH2ernandez @Leticia-Somera @danielgarcianu @BalfonsoBH

Agregados enlaces en pagina carrito

---

src/nosotros.html

Modificacion en el enlace de la imagen que lleva al index.html

Modificacion en el enlace de la^Cmagen que lleva al index.html

---

src/assets/css/carrito-style.css
src/assets/css/footer-style.css
src/carrito.html

Se hizo responsiva la pagina de carrito, se modifico el media query del footer para ajustarse al de bootstrap.

Carrito responsive y modificacion al query del footer

---

src/assets/css/login-style.css
src/assets/css/style-contacto.css
src/assets/js/validacion-login.js
src/login.html

Se suben algunos avances queda pendiente validación

---

src/assets/css/menu-style.css
src/assets/css/tienda-style.css
src/assets/js/tienda.js
src/tienda.html

@oscar10909 @KARLA-LEON @VictorH2ernandez @Leticia-Somera @danielgarcianu @AERA-Pik 
Se agregó el hoover de la imagen, se removió el de la card, corregidos problemas del responsive y las imagenes

Arreglada la pagina de la tienda

---

src/assets/css/nosotros.css
src/nosotros.html

Cambio del icono, ajuste de tamaño de tarjeta y se quita tarjeta "

Cambio del icono, Ajuste de tamaño de tarjeta y se quita tarjeta

---

src/assets/js/carrito.js
src/carrito.html
src/resumen.html

Se agregaron acentos a los textos del carrito de compras
@oscar10909 @KARLA-LEON @VictorH2ernandez @BalfonsoBH @AERA-Pik @010278Francisco

Acentos en miau carrito

---

src/.vscode/settings.json
src/assets/css/login-style.css
src/assets/js/validacion-login.js
src/login.html

Se suben actualizaciones login

---

src/assets/css/menu-style.css

Se modificó el cursor en el archivo CSS de la página del menú 
@oscar10909 @KARLA-LEON @VictorH2ernandez @AERA-Pik @BalfonsoBH @010278Francisco

Cambios en cursor del menú

---

src/assets/css/menu-style.css

Se modificó la extensión de la imagen para el cursor en la página de menú

Cambios en imagen de cursor del menú

---

src/.vscode/settings.json
src/assets/css/login-style.css
src/assets/js/validacion-login.js
src/login.html

Se sube login con validacion

---

src/carrito.html
src/resumen.html

Formato de HTML en carrito y resumen

Formato de HTML en carrito y resumen

---

src/nosotros.html

Se agrega un nuevo row para poder centrar la sección de tres tarjetas"

Se agrega un nuevo row para poder centrar la seccion de tres tarjetas

---

src/assets/css/styles.css
src/resumen.html

Se agrego cursor de patita al ccs general

Se agrego cursor de patita al ccs general

---

src/assets/css/menu-style.css
src/assets/js/menu.js
src/menu.html

Se comenta el código de la página del menú (menu.html, menu-stye.css y menu.js).
Se borra del archivo menu-style.css el body con la imagen del cursor personalizado.
Para que el cursor personalizado se muestre sobre la imagen de cada producto, se agrega la imagen del cursor al achivo menu-style.css en la etiqueta .menu .container-fluid .row .img-producto img.capa  
@oscar10909 @KARLA-LEON @VictorH2ernandez @AERA-Pik @BalfonsoBH @010278Francisco

Código del menú comentado

---

src/assets/css/login-style.css
src/assets/css/styles.css
src/assets/js/loader.js
src/login.html

Agrego mi push amiga @Leticia-Somera

Se suben cabios de loader 

---

src/assets/js/productos-prueba.json

Se subio un Archivo json con productos para pruebas de fetch en la tienda y el carrito.

Archivo json con productos para pruebas de fetch en la tienda y el carrito

---

src/assets/css/styles-home.css
src/index.html

Se agrega carrusel del Team Kitty Cakes modificando archivos index.html y styles-home.css
Se borran líneas de código del antiguo carrusel del Team en archivos index.html y styles-home.css
Se insertan enlaces en carrusel Team Kitty Cakes para redirigir a nosotros.html
Se quita el borde negro del carrusel inicial del  index.html 
Se modifica velocidad del carrusel inicial del  index.html a 900

Carrusel team kitty cakes

---

src/assets/css/styles-home.css
src/index.html
src/menu.html

Se realizaron los siguientes ajustes:
Quitar borde carrusel
Ajustar imágenes preview y que desaparezca una de ellas en dispositivos móviles
Ajuste de indicadores del carrusel
La imagen de promos del carrusel redirecciona a promos del menú, se agregó un #id al menu
@oscar10909 @VictorH2ernandez @Leticia-Somera @BalfonsoBH @010278Francisco @AERA-Pik

Ajustes index y redirección carrusel a menú

---

src/assets/css/styles-home.css

último ajuste imágenes preview

ajuste responsive imágenes preview
